server:
  port: 8080

spring:
  application:
    name: video
  datasource:
    url: jdbc:postgresql://localhost/videodb
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
    #initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update # options: create, create-drop, validate, update, none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #format_sql: true

aws:
  s3.bucket-name:
  access.key.id:
  secret.access.key:

#logging:
 # level:
#    org:
      #hibernate:
#        SQL: debug
#        type: trace

---

spring.config.activate.on-profile: docker

server.port: 80

spring:
  datasource:
    url: jdbc:postgresql://video-db:5432/videodb